Ignore possible zipbomb errors in releasetools
Some unzip versions try to detect zipbombs and block extracting those
archives. Unfortunately it also detects some false positives, so we need
to disable this behavior to avoid errors during 'm dist'.

  ExternalError: Failed to run command '['unzip', '-o', '-q', 'out/target/product/FP3/obj/PACKAGING/target_files_intermediates/fp3_gms-target_files-gms-251052bd.zip', '-d', 'out/soong/.temp/targetfiles-WLVWjh', 'SYSTEM/etc/vintf/*', 'VENDOR/etc/vintf/*', 'SYSTEM_EXT/etc/vintf/*', 'ODM/etc/*', 'META/*', '*/build.prop']' (exit code 12):
  error: invalid zip file with overlapped components (possible zip bomb)
   To unzip the file anyway, rerun the command with UNZIP_DISABLE_ZIPBOMB_DETECTION=TRUE environmnent variable

Change-Id: Ib24d7e7a6296d7f183bde07577068aa27d23fe0f